---
- name: Clone target
  git:
    repo: https://github.com/alkrauss48/growler-friday.git
    dest: /var/www/html/growler-friday

- name: Copy config
  template:
    src: templates/growlerfriday.conf.j2
    dest: /etc/nginx/sites-available/growlerfriday.conf

- name: Create sites-enabled symlink for nginx
  file:
    src: /etc/nginx/sites-available/growlerfriday.conf
    dest: /etc/nginx/sites-enabled/growlerfriday.conf
    state: link
  notify: restart nginx
